package main.evaluate;

public class EvaluationResult {
	
	/**
	 * This enum contains all 42 classes of the Neural Network
	 * Using german names since the request returns german names as well
	 * @author Jannik
	 *
	 */
	public static enum Sign{
		ZULAESSIGE_HOECHSTGESCHWINDIGKEIT_20,
		ZULAESSIGE_HOECHSTGESCHWINDIGKEIT_30,
		ZULAESSIGE_HOECHSTGESCHWINDIGKEIT_50,
		ZULAESSIGE_HOECHSTGESCHWINDIGKEIT_60,
		ZULAESSIGE_HOECHSTGESCHWINDIGKEIT_70,
		ZULAESSIGE_HOECHSTGESCHWINDIGKEIT_80,
		ENDE_DER_ZULAESSIGE_HOECHSTGESCHWINDIGKEIT_80,
		ZULAESSIGE_HOECHSTGESCHWINDIGKEIT_100,
		ZULAESSIGE_HOECHSTGESCHWINDIGKEIT_120,
		UEBERHOLVERBOT_ALLE,
		UEBERHOLVERBOT_LKW,
		VORFAHRT,
		VORFAHRTSSTRASSE,
		VORFAHRT_GEWAEHREN,
		STOP,
		FAHRVERBOT,
		LKW_VERBOT,
		EINFAHRT_VERBOT,
		GEFAHRSTELLE,
		KURVE_LINKS,
		KURVE_RECHTS,
		DOPPELKURVE_LINKS,
		UNEBENE_FAHRBAHN,
		SCHLEUDERGEFAHR,
		VERENGUNG_RECHTS,
		BAUSTELLE,
		LICHTZEICHENANLAGE,
		FUSSGAENGER,
		KINDER,
		RADVERKEHR,
		SCHNEEGLAETTE,
		WILDWECHSEL,
		ENDE_ALLER_VERBOTE,
		FAHRTRICHTUNG_RECHTS,
		FAHRTRICHTUNG_LINKS,
		FAHRTRICHTUNG_GERADE,
		FAHRTRICHTUNG_GERADE_RECHTS,
		FAHRTRICHTUNG_GERADE_LINKS,
		FAHRTRICHTUNG_RECHTS_VORBEI,
		FAHRTRICHTUNG_LINKS_VORBEI,
		KREISVERKEHR,
		ENDE_UEBERHOLVERBOT,
		ENDE_UEBERHOLVERBOT_LKW
	}
	
	/**
	 * Return the name of a Sign
	 * @param s the sign which name is required
	 * @return the name
	 */
	public static String getNameOfSign(Sign s) {
		return s.toString();
	}
	
}
